name: 'Weekly Workflow'

on: workflow_dispatch

jobs:
  Upload_Job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
          ./triggerRun.sh ${{ vars.PLAYLIST_ONE }}