name: 'Weekly Workflow'

on:
  schedule:
    - cron: "32 7 * * 2"

jobs:
  Upload_Job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Execute Program
        run: ./triggerRun.sh ${{ vars.PLAYLIST_ONE }}