name: 'Weekly Workflow'

on:
  schedule:
    - cron: "56 9 * * *"

jobs:
  Upload_Job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Execute Program
        run: npm install
        run: ./triggerRun.sh ${{ vars.PLAYLIST_ONE }} ${{ vars.GIT_EMAIL }} ${{ vars.GIT_USERNAME }}