name: 'Weekly Workflow'

on: workflow_dispatch

jobs:
  Upload_Job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install 

      - name: Execute Program 
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: ./triggerRun.sh ${{ vars.PLAYLIST_ONE }} ${{ vars.GIT_EMAIL }} ${{ vars.GIT_USERNAME }} ${{ github.ref_name }}