name: 'Upload Episode from YouTube To Anchor.Fm'

on:
  push:
    paths:
      - episode.json
    branches: 
      - debug-dup

jobs:
  Upload_Job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: convertedVideos
          path: convertedVideos.json

      - name: Upload Episode from YouTube To Anchor.Fm
        uses: Schrodinger-Hat/youtube-to-anchorfm@v2.0.0
        env:
          ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL_local-cron }}
          ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD_local-cron }}
          EPISODE_PATH: /github/workspace
          SAVE_AS_DRAFT: true # Remove to publish directly
          LOAD_THUMBNAIL: true # Remove if thumbnail is not required as episode art
          SET_PUBLISH_DATE: true # Sets publishing date
          URL_IN_DESCRIPTION: true # Sets youtube URL to episode description