name: 'Upload Episode from YouTube To Anchor.Fm'

on:
  workflow_dispatch
  # push:
  #   paths: 
  #     - episode.json
  #   branches: [main]

jobs:
  upload_episode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Download Playlist HTML  
        run: |
          wget https://www.youtube.com/watch?v=ABbDB6xri8o&list=PLrAXtmErZgOcl7mvyfkQTHFnOGZxWtN55

      - name: Rename the Download
        run: mv *watch* playlist.html && ls -sal

      - name: Setup Node
        run: |
          sudo apt-get update && \
          sudo apt-get install nodejs && \
          node --version
      
      - name: Extract Video IDs
        run: node generateEpisodeList.mjs
      # - name: Upload Episode from YouTube To Anchor.Fm
      #   uses: Schrodinger-Hat/youtube-to-anchorfm@v2.0.0
      #   env:
      #     ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
      #     ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}
      #     EPISODE_PATH: /github/workspace
      #     SAVE_AS_DRAFT: true # Remove if not required
      #     LOAD_THUMBNAIL: true # Remove if thumbnail is not required as episode art
      #     SET_PUBLISH_DATE: true # Sets publishing date 