name: 'Upload Episode from YouTube To Anchor.Fm'

on:
  push:
    paths:
      - episode.json
    branches: 
      - main

jobs:
  Upload_Job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: convertedVideos
          path: convertedVideos.json

      - name: Upload Episode from YouTube To Anchor.Fm
        uses: Schrodinger-Hat/youtube-to-anchorfm@v2.0.0
        env:
          ANCHOR_EMAIL: ${{ secrets.ANCHOR_EMAIL }}
          ANCHOR_PASSWORD: ${{ secrets.ANCHOR_PASSWORD }}
          EPISODE_PATH: /github/workspace
          SAVE_AS_DRAFT: true # Remove before handover
          LOAD_THUMBNAIL: true # Remove if thumbnail is not required as episode art
          SET_PUBLISH_DATE: true # Sets publishing date
  
  Processed_Success:
    runs-on: ubuntu-latest
    needs: Upload_Job
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: convertedVideos

      - name: Commit status change of converted videos      
        run: |
          git add convertedVideos.json && \
          git commit -m "After successful conversion of videos" && \
          git push 